// flow-typed signature: 29d0272c6392ee7fbd22319c647566ba
// flow-typed version: <<STUB>>/victor_v^1.1.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'victor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'victor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'victor/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'victor/index' {
  declare module.exports: $Exports<'victor'>;
}
declare module 'victor/index.js' {
  declare module.exports: $Exports<'victor'>;
}
declare module 'victor/test.js' {
  declare module.exports: $Exports<'victor/test'>;
}
